insert into InstrumentDataID(ID, Name) values(1, 'South Africa 40');
insert into InstrumentDataID(ID, Name) values(2, 'EU Stocks 50');
insert into InstrumentDataID(ID, Name) values(3, 'US 500');
insert into InstrumentDataID(ID, Name) values(4, 'Japan 225');
insert into InstrumentDataID(ID, Name) values(5, 'Hong Kong HS50');
insert into InstrumentDataID(ID, Name) values(6, 'Australia 200');
insert into InstrumentDataID(ID, Name) values(7, 'FTSE 100');
insert into InstrumentDataID(ID, Name) values(8, 'Germany 30');
insert into InstrumentDataID(ID, Name) values(9, 'China A50');
insert into InstrumentDataID(ID, Name) values(10, 'India 50');
insert into InstrumentDataID(ID, Name) values(11, 'EUR/USD');
insert into InstrumentDataID(ID, Name) values(12, 'GBP/USD');
insert into InstrumentDataID(ID, Name) values(13, 'Brent Crude');
insert into InstrumentDataID(ID, Name) values(14, 'Copper');
insert into InstrumentDataID(ID, Name) values(15, 'Iron Ore');
insert into InstrumentDataID(ID, Name) values(16, 'Spot Gold');
insert into InstrumentDataID(ID, Name) values(17, 'Platinum');
insert into InstrumentDataID(ID, Name) values(18, 'Paris Milling Wheat');
insert into InstrumentDataID(ID, Name) values(19, 'Corn');
insert into InstrumentDataID(ID, Name) values(20, 'Live Cattle');
insert into InstrumentDataID(ID, Name) values(21, 'USD/CAD');
insert into InstrumentDataID(ID, Name) values(22, 'USD/JPY');
